linters:
  enable:
    - gofmt # Formatting
    - goimports # Imports ordering
    - govet # Suspicious constructs
    - errcheck # Error handling
    - staticcheck # Static analysis
    - gosimple # Simplifications
    - ineffassign # Ineffective assignments
    - unused # Unused code
    - misspell # Spelling
    - whitespace # Whitespace style

run:
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/GevorgGal/webcrawler

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
